// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCry64uCA3z3hyWG-VTwwpSIIwoCjaVZTQ',
    appId: '1:177068114628:web:d438167fb829d593187f91',
    messagingSenderId: '177068114628',
    projectId: 'cak1r-s-project',
    authDomain: 'cak1r-s-project.firebaseapp.com',
    storageBucket: 'cak1r-s-project.appspot.com',
    measurementId: 'G-4WT087JDQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwp-fSt-OxF7z7idF89PhEUvw64Z57wA',
    appId: '1:177068114628:android:68bc8811505c2ab0187f91',
    messagingSenderId: '177068114628',
    projectId: 'cak1r-s-project',
    storageBucket: 'cak1r-s-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd4IyLYeR3kq_09FtWtSupDSj-eRpsFps',
    appId: '1:177068114628:ios:1327236dfbe972da187f91',
    messagingSenderId: '177068114628',
    projectId: 'cak1r-s-project',
    storageBucket: 'cak1r-s-project.appspot.com',
    iosClientId: '177068114628-85133lruk0309o175da4jl2bos0t8ba8.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd4IyLYeR3kq_09FtWtSupDSj-eRpsFps',
    appId: '1:177068114628:ios:1327236dfbe972da187f91',
    messagingSenderId: '177068114628',
    projectId: 'cak1r-s-project',
    storageBucket: 'cak1r-s-project.appspot.com',
    iosClientId: '177068114628-85133lruk0309o175da4jl2bos0t8ba8.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
